### ISSUE TITLE
TypeError: sequence item 0: expected string or Unicode, Alias found

### ISSUE THREAD

**Issue by Turbo87** [skylines-project/skylines#290]
App:                skylines.frontend
Time:               2014-03-16 12:59:28,684
URL:                https://www.skylines-project.org/flights/8663/

Message:

```
Exception on /flights/8663/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/skylines/src/skylines/frontend/views/flight.py", line 210, in index
    phase_formatter=format_phase)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 736, in handle_exception
    traceback = _make_traceback(exc_info, source_hint)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/debug.py", line 140, in make_traceback
    return translate_exception(exc_info, initial_skip)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/debug.py", line 193, in translate_exception
    reraise(exc_info[0], exc_info[1], exc_info[2])
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 966, in render
    return concat(self.root_render_func(self.new_context(vars)))
TypeError: sequence item 0: expected string or Unicode, Alias found
```

**Comment by Turbo87** [comment]
obsolete
