### ISSUE TITLE
Flight uploads freeze the python process

### ISSUE THREAD

**Issue by Turbo87** [skylines-project/skylines#395]
It looks like sometimes flight uploads freeze the live server and occasionally I can reproduce it with the `upload_test.py` script and `py.test`.

I have used the instructions at http://stackoverflow.com/a/147114/1478093 to get a stacktrace from the frozen process:

```
(gdb) bt
#0  AsDelta (this=<optimized out>) at src/Math/Angle.cpp:120
#1  Angle::Fraction (this=0x3ec73c0, end=..., fraction=0.5) at src/Math/Angle.cpp:156
#2  0x00007f1a4938fc23 in TaskProjection::Update (this=0x3ec73b0) at src/Geo/Flat/TaskProjection.cpp:75
#3  0x00007f1a49382c8c in Airspaces::Optimise (this=0x3ec7360) at src/Engine/Airspace/Airspaces.cpp:208
#4  0x00007f1a4937e902 in xcsoar_Airspaces_optimise (self=<optimized out>) at python/src/Airspaces.cpp:199
#5  0x000000000056e00c in PyEval_EvalFrameEx ()
#6  0x00000000005747c0 in PyEval_EvalCodeEx ()
#7  0x000000000056da48 in PyEval_EvalFrameEx ()
#8  0x000000000056dc92 in PyEval_EvalFrameEx ()
#9  0x00000000005747c0 in PyEval_EvalCodeEx ()
#10 0x00000000005698e2 in ?? ()
#11 0x000000000043a8b6 in PyObject_Call ()
#12 0x000000000056f247 in PyEval_EvalFrameEx ()
#13 0x00000000005747c0 in PyEval_EvalCodeEx ()
#14 0x00000000005698e2 in ?? ()
#15 0x000000000043a8b6 in PyObject_Call ()
#16 0x000000000056f247 in PyEval_EvalFrameEx ()
#17 0x000000000056dc92 in PyEval_EvalFrameEx ()
#18 0x000000000056dc92 in PyEval_EvalFrameEx ()
#19 0x000000000056dc92 in PyEval_EvalFrameEx ()
#20 0x00000000005747c0 in PyEval_EvalCodeEx ()
#21 0x000000000056da48 in PyEval_EvalFrameEx ()
#22 0x00000000005747c0 in PyEval_EvalCodeEx ()
#23 0x000000000056da48 in PyEval_EvalFrameEx ()
#24 0x00000000005747c0 in PyEval_EvalCodeEx ()
#25 0x000000000056da48 in PyEval_EvalFrameEx ()
#26 0x00000000005747c0 in PyEval_EvalCodeEx ()
#27 0x000000000056da48 in PyEval_EvalFrameEx ()
#28 0x00000000005747c0 in PyEval_EvalCodeEx ()
```

see https://github.com/XCSoar/XCSoar/blob/c230722/src/Math/Angle.cpp#L120

**Comment by Turbo87** [comment]
@TobiasLohner any ideas?

**Comment by Turbo87** [comment]
that was fixed by https://github.com/skylines-project/py-xcsoar/pull/23 and https://github.com/XCSoar/XCSoar/commit/0f7de0cd927daeabd3972d918e1a9e44887b5613
