### ISSUE TITLE
Traceback in daemon err

### ISSUE THREAD

**Issue by lordfolken** [skylines-project/skylines#403]
Traceback (most recent call last): 

```
  File "/home/skylines/virtualenv/local/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run 
    result = self._run(*self.args, **self.kwargs) 
  File "/home/skylines/src/skylines/tracking/server.py", line 267, in handle 
    self.fixReceived(host, header[3], data[16:]) 
  File "/home/skylines/src/skylines/tracking/server.py", line 72, in fixReceived 
    pilot = User.by_tracking_key(key) 
  File "/home/skylines/src/skylines/model/user.py", line 119, in by_tracking_key 
    return cls.query(tracking_key=key).first() 
  File "/home/skylines/virtualenv/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2278, in first 
    ret = list(self[0:1]) 
  File "/home/skylines/virtualenv/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2145, in __getitem__ 
    return list(res) 
  File "/home/skylines/virtualenv/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2349, in __iter__ 
    return self._execute_and_instances(context) 
  File "/home/skylines/virtualenv/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2364, in _execute_and_instances 
    result = conn.execute(querycontext.statement, self._params) 
  File "/home/skylines/virtualenv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 662, in execute 
    params) 
  File "/home/skylines/virtualenv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 761, in _execute_clauseelement 
    compiled_sql, distilled_params 
  File "/home/skylines/virtualenv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 874, in _execute_context 
    context) 
  File "/home/skylines/virtualenv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1024, in _handle_dbapi_exception 
    exc_info 
  File "/home/skylines/virtualenv/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 195, in raise_from_cause 
    reraise(type(exception), exception, tb=exc_tb) 
  File "/home/skylines/virtualenv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 867, in _execute_context 
    context) 
  File "/home/skylines/virtualenv/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 324, in do_execute 
    cursor.execute(statement, parameters) 
OperationalError: (OperationalError) server closed the connection unexpectedly 
        This probably means the server terminated abnormally 
        before or while processing the request. 
 'SELECT users.email_address AS users_email_address, users.password AS users_password, users.id AS users_id, users.first_name AS users_first_name, users.last_name AS users_last_name, users.club_id AS users_club_id, users.tracking_key AS users_tracking_key, users.tracking_delay AS users_tracking_delay, users.tracking_callsign AS users_tracking_callsign, users.created AS users_created, users.created_ip AS users_created_ip, users.login_time AS users_login_time, users.login_ip AS users_login_ip, users.recover_key AS users_recover_key, users.recover_time AS users_recover_time, users.recover_ip AS users_recover_ip, users.distance_unit AS users_distance_unit, users.speed_unit AS users_speed_unit, users.lift_unit AS users_lift_unit, users.altitude_unit AS users_altitude_unit, users.admin AS users_admin \nFROM users \nWHERE users.tracking_key = %(tracking_key_1)s \n LIMIT %(param_1)s' {'param_1': 1, 'tracking_key_1': 3542354914}
<Greenlet at 0x7f4cb385ec30: <bound method TrackingServer.handle of <TrackingServer at 0x7f4cb37f5a10 fileno=5 address=0.0.0.0:5597>>(']\xf4\xb6{\x1c\x1b\x00\x03\x00\x00\x00\x00\xd3$\x, ('46.114.132.143', 40211))> failed with OperationalError
```

Traceback (most recent call last):

```
  File "/home/skylines/virtualenv/local/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/skylines/src/skylines/tracking/server.py", line 267, in handle
    self.fixReceived(host, header[3], data[16:])
  File "/home/skylines/src/skylines/tracking/server.py", line 72, in fixReceived
    pilot = User.by_tracking_key(key)
  File "/home/skylines/src/skylines/model/user.py", line 119, in by_tracking_key
    return cls.query(tracking_key=key).first()
  File "/home/skylines/virtualenv/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2278, in first
    ret = list(self[0:1])
  File "/home/skylines/virtualenv/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2145, in __getitem__
    return list(res)
  File "/home/skylines/virtualenv/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2349, in __iter__
    return self._execute_and_instances(context)
  File "/home/skylines/virtualenv/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2362, in _execute_and_instances
    close_with_result=True)
  File "/home/skylines/virtualenv/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2353, in _connection_from_session
    **kw)
  File "/home/skylines/virtualenv/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 799, in connection
    close_with_result=close_with_result)
  File "/home/skylines/virtualenv/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 803, in _connection_for_bind
    return self.transaction._connection_for_bind(engine)
  File "/home/skylines/virtualenv/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 299, in _connection_for_bind
    conn = bind.contextual_connect()
  File "/home/skylines/virtualenv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1661, in contextual_connect
    self.pool.connect(),
  File "/home/skylines/virtualenv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 272, in connect
    return _ConnectionFairy(self).checkout()
  File "/home/skylines/virtualenv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 425, in __init__
    rec = self._connection_record = pool._do_get()
  File "/home/skylines/virtualenv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 778, in _do_get
    con = self._create_connection()
  File "/home/skylines/virtualenv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 225, in _create_connection
    return _ConnectionRecord(self)
  File "/home/skylines/virtualenv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 318, in __init__
    self.connection = self.__connect()
  File "/home/skylines/virtualenv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 368, in __connect
    connection = self.__pool._creator()
  File "/home/skylines/virtualenv/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 80, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/skylines/virtualenv/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 283, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/skylines/virtualenv/local/lib/python2.7/site-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
OperationalError: (OperationalError) could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
 None None
<Greenlet at 0x7f4cb385ec30: <bound method TrackingServer.handle of <TrackingServer at 0x7f4cb37f5a10 fileno=5 address=0.0.0.0:5597>>(']\xf4\xb6{nP\x00\x03\x00\x00\x00\x00\x8d\x8aO\xe0, ('2.54.183.32', 60499))> failed with OperationalError
```

Traceback (most recent call last):

```
  File "/home/skylines/virtualenv/local/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/skylines/src/skylines/tracking/server.py", line 268, in handle
    self.fix_received(host, header[3], data[16:])
  File "/home/skylines/src/skylines/tracking/server.py", line 109, in fix_received
    fix.elevation = Elevation.get(fix.location_wkt)
  File "/home/skylines/src/skylines/model/elevation.py", line 27, in get
    return query.scalar()
  File "/home/skylines/virtualenv/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2337, in scalar
    ret = self.one()
  File "/home/skylines/virtualenv/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2315, in one
    "Multiple rows were found for one()")
MultipleResultsFound: Multiple rows were found for one()
<Greenlet at 0x7f582cc40d70: <bound method TrackingServer.handle of <TrackingServer at 0x7f582cda0190 fileno=5 address=0.0.0.0:5597>>(']\xf4\xb6{\x80\xca\x00\x03\x00\x00\x00\x00\x9d\x9, ('166.176.187.231', 7225))> failed with MultipleResultsFound
```

**Comment by Turbo87** [comment]
@lordfolken where does that come from?
