### ISSUE TITLE
unable to build project

### ISSUE THREAD

**Issue by jharting** [skylines-project/skylines#441]
when running `./manage.py assets build` I am running into:

```
$ ./manage.py assets build
Generating bundle: js/ember-app-%(version)s.js
Traceback (most recent call last):
  File "./manage.py", line 6, in <module>
    manager.run()
  File "/usr/lib/python2.7/site-packages/flask_script/__init__.py", line 423, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/usr/lib/python2.7/site-packages/flask_script/__init__.py", line 402, in handle
    return handle(app, *positional_args, **kwargs)
  File "/usr/lib/python2.7/site-packages/flask_script/commands.py", line 145, in handle
    return self.run(*args, **kwargs)
  File "/home/jharting/projects/skylines/skylines/commands/assets.py", line 17, in build
    bundle.build()
  File "/usr/lib/python2.7/site-packages/webassets/bundle.py", line 563, in build
    disable_cache=disable_cache))
  File "/usr/lib/python2.7/site-packages/webassets/bundle.py", line 498, in _build
    force, disable_cache=disable_cache, extra_filters=extra_filters)
  File "/usr/lib/python2.7/site-packages/webassets/bundle.py", line 355, in _merge_and_apply
    resolved_contents = self.resolve_contents(env, force=True)
  File "/usr/lib/python2.7/site-packages/webassets/bundle.py", line 148, in resolve_contents
    raise BundleError(e)
webassets.exceptions.BundleError: 'ember/assets/skylines.js' not found in load path: ['/home/jharting/projects/skylines/skylines/frontend/static']
```

Happens both when running in my local environment and also in vagrant. Any idea what I am doing wrong?

**Comment by jharting** [comment]
Apparently what I was missing was:

```
cd ember
npm install
bower install
./node_modules/ember-cli/bin/ember build
```

**Comment by Turbo87** [comment]
yeah, sorry about that. I'm currently in the process of converting the project from mainly server-rendered via Flask to client-rendered via [Ember](http://emberjs.com/) with Flask only providing an API. the build instructions currently don't reflect those changes since they hopefully will change a bit again once that process is finished.

**Comment by kerel-fs** [comment]
I'm trying to fix this issue, unfortunately I'm stuck with the following error message:
```
ubuntu@ubuntu-xenial:/vagrant/ember$ ember build  
Cannot find module './code-path-analysis/code-path-analyzer'
Error: Cannot find module './code-path-analysis/code-path-analyzer'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/vagrant/ember/node_modules/ember-cli-eslint/node_modules/broccoli-lint-eslint/node_modules/eslint/lib/eslint.js:20:24)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
ubuntu@ubuntu-xenial:/vagrant/ember$ npm --version
3.5.2
ubuntu@ubuntu-xenial:/vagrant/ember$ nodejs --version
v4.2.6
```
My updated [Vagrantfile](https://github.com/kerel-fs/skylines/blob/fix/vagrant/Vagrantfile) is based on the official `Ubuntu/xenial64` base box and installs a working node.js v4 environment. Any ideas how to fix the error above?

**Comment by Turbo87** [comment]
@kerel-fs a few thoughts on that:

- the Vagrantfile was using the old ubuntu version on purpose (though I admit that I am a bit annoyed by it too), because TravisCI is using the same version for their CI workers. It might be possible to upgrade that as well though, but that is unrelated to this issue

- how did you install `node`? my recommended way right now is using `nvm` (https://github.com/creationix/nvm). in other words `curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.32.0/install.sh | bash` and then `nvm install 6` to install Node 6.x

- once Node is installed you will have to `npm install && bower install` to install the required build dependencies, after that there shouldn't be any issues left for `ember build`

**Comment by kerel-fs** [comment]
Thanks for your answer.

Last time I installed `node` from the official ubuntu package repositories (v4.2.5, as suggested by [ember/.travis.yml](https://github.com/skylines-project/skylines/blob/master/ember/.travis.yml#L4) and [ember/packages.json](https://github.com/skylines-project/skylines/blob/master/ember/package.json#L17)).

This time I use `nvm` to install node.js v6 in an Ubuntu Precise Pangolin base image as you recommended.
`npm install` works, but unfortunately `bower install` doesn't create any output (I had to install `bower` manually with `npm install -g bower`).
Do you have any more hints?

I updated the [Vagrantfile](https://github.com/kerel-fs/skylines/blob/fix/vagrant/Vagrantfile) according to your recommendations.

**Comment by Turbo87** [comment]
> Do you have any more hints?

that should be all that's necessary. is anything else failing with that approach?

**Comment by kerel-fs** [comment]
Yes, `ember build` fails again with
```
vagrant@vagrant-ubuntu-precise-64:/vagrant/ember$ ./node_modules/ember-cli/bin/ember build
Cannot find module './code-path-analysis/code-path-analyzer'
Error: Cannot find module './code-path-analysis/code-path-analyzer'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/vagrant/ember/node_modules/ember-cli-eslint/node_modules/broccoli-lint-eslint/node_modules/eslint/lib/eslint.js:20:24)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
vagrant@vagrant-ubuntu-precise-64:/vagrant/ember$ npm --version
3.10.3
vagrant@vagrant-ubuntu-precise-64:/vagrant/ember$ node --version                              
v6.6.0
```

**Comment by kerel-fs** [comment]
My current guess: `npm install`doesn't complete without errors, thus some modules aren't installed correctly. Eventually some dependency can't be installed for Ubuntu Precise Pangolin.
@jharting Could you provide some information about your environment if it works for you?

**Comment by Turbo87** [comment]
@kerel-fs I was able to fix it. The issue was apparently that NPM got killed because it used to much memory. I increased the memory size that vagrant is using for the virtualbox machine and now it seems to run through. the commits are at https://github.com/Turbo87/skylines/commits/fix/vagrant, feel free to open a PR :)

**Comment by kerel-fs** [comment]
Apparently a memory size of 1024 MB isn't enough for `npm install`. m(
The issue is tracked by npm/npm#9884. I will open a PR.

**Comment by Turbo87** [comment]
yeah... NPM is a special little snowflake... 😕
