### ISSUE TITLE
TypeError: Cannot read property 'id' of null

### ISSUE THREAD

**Issue by Turbo87** [skylines-project/skylines#509]
https://sentry.io/skylines/skylines/issues/173996807/

```
TypeError: Cannot read property 'id' of null
  at set(bower_components/ember/ember.prod.js:20058:0)
  at _emberMetal(bower_components/ember/ember.prod.js:13306:0)
  at keyName(bower_components/ember/ember.prod.js:6330:0)
  at propertyDidChange(bower_components/ember/ember.prod.js:19696:0)
  at set(bower_components/ember/ember.prod.js:20086:0)
  at set(bower_components/ember/ember.prod.js:32484:0)
  at call(skylines/components/settings-panels/choose-club.js:22:0)   <---
  at _set(bower_components/ember/ember.prod.js:15218:0)
  at setWithSuspend(bower_components/ember/ember.prod.js:15198:0)
  at set(bower_components/ember/ember.prod.js:15176:0)
  at set(bower_components/ember/ember.prod.js:20070:0)
  at apply(bower_components/ember/ember.prod.js:13247:0)
  at apply(bower_components/ember/ember.prod.js:698:0)
  at apply(bower_components/ember/ember.prod.js:735:0)
  at apply(bower_components/ember/ember.prod.js:20303:0)
  at callback(bower_components/ember/ember.prod.js:8717:0)
  at flaggedInstrument(bower_components/ember/ember.prod.js:16560:0)
  at selected(bower_components/ember/ember.prod.js:8716:0)
  at apply(ember-power-select/components/power-select.js:267:0)
  at apply(bower_components/ember/ember.prod.js:36715:0)
  at apply(bower_components/ember/ember.prod.js:36478:0)
  at select(ember-power-select/components/power-select.js:102:0)
  at apply(ember-power-select/components/power-select.js:290:0)
  at apply(bower_components/ember/ember.prod.js:36715:0)
  at apply(bower_components/ember/ember.prod.js:36478:0)
  at action(ember-power-select/components/power-select.js:109:0)
  at findOptionAndPerform(ember-power-select/components/power-select/options.js:28:0)
  at apply(ember-power-select/components/power-select/options.js:31:0)
  at apply(bower_components/raven-js/dist/raven.js:351:0)
```

**Comment by Turbo87** [comment]
this looks similar to #516, but seems harder to reproduce.

**Comment by Turbo87** [comment]
... he said, and then found a way to reproduce this.

- go to settings with a user without a club
- try to select a club
- 💥
