### ISSUE TITLE
Error: Invalid dimensions for plot, width = 0, height = 133

### ISSUE THREAD

**Issue by Turbo87** [skylines-project/skylines#510]
https://sentry.io/skylines/skylines/issues/166599365/

```
Error: Invalid dimensions for plot, width = 0, height = 133
  at resize(bower_components/Flot/jquery.flot.js:135:0)
  at new t(bower_components/Flot/jquery.flot.js:114:0)
  at setupCanvases(bower_components/Flot/jquery.flot.js:1313:0)
  at new n(bower_components/Flot/jquery.flot.js:707:0)
  at plot(bower_components/Flot/jquery.flot.js:3146:0)
  at apply(skylines/components/base-barogram.js:71:0)   <--
  at apply(skylines/components/flight-barogram.js:89:0)   <--
  at apply(bower_components/ember/ember.prod.js:36478:0)
  at apply(bower_components/ember/ember.prod.js:38248:0)
  at trigger(bower_components/ember/ember.prod.js:36478:0)
  at didCreate(bower_components/ember/ember.prod.js:11199:0)
  at call(bower_components/ember/ember.prod.js:47286:0)
  at commit(bower_components/ember/ember.prod.js:8106:0)
  at _renderRoots(bower_components/ember/ember.prod.js:10701:0)
  at _renderRootsTransaction(bower_components/ember/ember.prod.js:10730:0)
  at call(bower_components/ember/ember.prod.js:10769:0)
  at invoke(bower_components/ember/ember.prod.js:337:0)
  at flush(bower_components/ember/ember.prod.js:396:0)
  at flush(bower_components/ember/ember.prod.js:520:0)
  at end(bower_components/ember/ember.prod.js:590:0)
  at apply(bower_components/ember/ember.prod.js:704:0)
  at apply(bower_components/ember/ember.prod.js:735:0)
  at join(bower_components/ember/ember.prod.js:20303:0)
  at apply(ember-ajax/mixins/ajax-request.js:235:0)
  at fire(bower_components/jquery/jquery.js:3048:0)
  at resolveWith(bower_components/jquery/jquery.js:3160:0)
  at complete(bower_components/jquery/jquery.js:8235:0)
  at complete(bower_components/jquery/jquery.js:8778:0)
```

**Comment by Turbo87** [comment]
no idea yet how to reproduce this...

**Comment by lordfolken** [comment]
Closing as stale/wontfix in 2026 revitalization triage; reopen with fresh repro if still relevant.
