### ISSUE TITLE
Vagrantfile broken

### ISSUE THREAD

**Issue by pyrog** [skylines-project/skylines#563]
Vagrant can't install skylines (on **macOS Sierra**)

```
vagrant up
…
==> default: Installing collected packages: SkyLines
==> default:   Found existing installation: SkyLines 0.1.0
==> default:     Can't uninstall 'SkyLines'. No files were found to uninstall.
==> default:   Running setup.py develop for SkyLines
==> default: Successfully installed SkyLines
```

Run fine until that point :
```
==> default: Missing binding /vagrant/ember/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/node-sass/vendor/linux-x64-46/binding.node
==> default: Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 4.x
==> default: 
==> default: Found bindings for the following environments:
==> default:   - OS X 64-bit with Node.js 4.x
==> default: 
==> default: This usually happens because your environment has changed since running `npm install`.
==> default: Run `npm rebuild node-sass` to build the binding for your current environment.
==> default: Error: Missing binding /vagrant/ember/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/node-sass/vendor/linux-x64-46/binding.node
==> default: Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 4.x
==> default: 
==> default: Found bindings for the following environments:
==> default:   - OS X 64-bit with Node.js 4.x
==> default: 
==> default: This usually happens because your environment has changed since running `npm install`.
==> default: Run `npm rebuild node-sass` to build the binding for your current environment.
==> default:     at Object.<anonymous> (/vagrant/ember/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/node-sass/lib/index.js:15:11)
==> default:     at Module._compile (module.js:409:26)
==> default:     at Object.Module._extensions..js (module.js:416:10)
==> default:     at Module.load (module.js:343:32)
==> default:     at Function.Module._load (module.js:300:12)
==> default:     at Module.require (module.js:353:17)
==> default:     at require (internal/module.js:12:17)
==> default:     at Object.<anonymous> (/vagrant/ember/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/index.js:5:16)
==> default:     at Module._compile (module.js:409:26)
==> default:     at Object.Module._extensions..js (module.js:416:10)
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

```

Try `npm rebuild node-sass`
Then  `vagrant provision`. The script restart but stop at the same point 😞

**Comment by Turbo87** [comment]
Remove the `node_modules` folder in the `ember` folder and try again. I assume you've run `npm install` on OSX and running `npm install` inside the Linux VM in the shared folder is causing these issues.

**Comment by pyrog** [comment]
> I assume you've run npm install on OSX and running npm install inside the Linux VM in the shared folder is causing these issues.

Probably that.

Restart vagrant. Better but the script is locked at this stage.
```
==> default: "/vagrant/ember/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/node-sass/vendor/linux-x64-46/binding.node" exists. 
==> default:  testing binary.
==> default: Binary is fine; exiting.

```

This message is displayed every 15 secondes in the VirtualBox machine:
![virtualbox_skylines_default_1478770456176_20366_10_11_2016_14_08_36](https://cloud.githubusercontent.com/assets/2158081/20178100/0f60b546-a750-11e6-8d9c-71acaf003572.png)

**Comment by pyrog** [comment]
Remove everything. Download a fresh copy of skylines-master.

Got **ERROR:  could not open extension control file "/usr/share/postgresql/9.4/extension/postgis.control": No such file or directory**

```
==> default: font-awesome#4.5.0 bower_components/font-awesome
==> default: Could not start watchman; falling back to NodeWatcher for file system events.
==> default: Visit http://ember-cli.com/user-guide/#watchman for more info.
==> default: Built project successfully. Stored in "../skylines/frontend/static".
==> default: ERROR:  could not open extension control file "/usr/share/postgresql/9.4/extension/postgis.control": No such file or directory
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

```

**Comment by pyrog** [comment]
Seem finded a solution 😄 

Change this in Vagrantfile:

```
# install base dependencies

sudo apt-get install -y --no-install-recommends \
    g++-6 pkg-config libcurl4-openssl-dev python-dev git redis-server \
    libpq-dev postgresql-9.5-postgis-2.2 postgresql-9.5-postgis-2.2-scripts postgresql-contrib-9.5 \
    openjdk-7-jre-headless libfreetype6-dev libpng-dev libffi-dev

```

Vagrant is running, I'll tell you tomorrow if I could close this issue 😉
