### ISSUE TITLE
ImportError: No module named osgeo

### ISSUE THREAD

**Issue by pyrog** [skylines-project/skylines#568]
Related to  #538 (#563 ?)

In vagrant, try to import manually airspaces:

`./manage.py import airspace --country at --filetype openair --url https://www.austrocontrol.at/jart/prj3/austro_control/data/dokumente/aV5XF_AustriaAirspaceMainFileeffdate01052015-27052015V.1.00.txt`

Got:

```
Traceback (most recent call last):
  File "./manage.py", line 6, in <module>
    manager.run()
  File "/usr/local/lib/python2.7/dist-packages/flask_script/__init__.py", line 423, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/flask_script/__init__.py", line 402, in handle
    return handle(app, *positional_args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_script/commands.py", line 145, in handle
    return self.run(*args, **kwargs)
  File "/vagrant/skylines/commands/import_/airspace.py", line 112, in run
    self.import_airspace(url, country[0], filetype, debug)
  File "/vagrant/skylines/commands/import_/airspace.py", line 175, in import_airspace
    self.import_openair(filename, country_code, debug)
  File "/vagrant/skylines/commands/import_/airspace.py", line 262, in import_openair
    from osgeo import ogr
ImportError: No module named osgeo
```

Found this: http://stackoverflow.com/questions/29852857/no-module-named-osgeo-ogr

**Comment by kerel-fs** [comment]
This bug is still existent. It's a known problem of GDAL when a python virtual environment is used.

See also
https://gist.github.com/cspanring/5680334
which recommends to have a look at
https://stackoverflow.com/a/38603825

Unfortunately I wasn't able to get it fixed.

Command to reproduce (from [INSTALL.mapserver.md](https://github.com/skylines-project/skylines/blob/master/INSTALL.mapserver.md)):
```
vagrant@vagrant-ubuntu-precise-64:/vagrant$ pipenv run ./manage.py import airspace mapserver/airspace/airspace_list.txt mapserver/airspace/airspace_blacklist.txt

Downloading https://www.daec.de/fileadmin/user_upload/files/2018/Fachbereiche/Luftraum_und_Flugbetrieb/Airspace_Germany_week13_2018_V2_ohneFIS.txt
removing all entries for country_code de
/home/vagrant/.local/share/virtualenvs/vagrant-gKDsaKU3/local/lib/python2.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
Traceback (most recent call last):
  File "./manage.py", line 6, in <module>
    manager.run()
  File "/home/vagrant/.local/share/virtualenvs/vagrant-gKDsaKU3/local/lib/python2.7/site-packages/flask_script/__init__.py", line 423, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/home/vagrant/.local/share/virtualenvs/vagrant-gKDsaKU3/local/lib/python2.7/site-packages/flask_script/__init__.py", line 402, in handle
    return handle(app, *positional_args, **kwargs)
  File "/home/vagrant/.local/share/virtualenvs/vagrant-gKDsaKU3/local/lib/python2.7/site-packages/flask_script/commands.py", line 145, in handle
    return self.run(*args, **kwargs)
  File "/vagrant/skylines/commands/import_/airspace.py", line 134, in run
    self.import_airspace(url, country_code, file_type, debug)
  File "/vagrant/skylines/commands/import_/airspace.py", line 177, in import_airspace
    self.import_openair(filename, country_code, debug)
  File "/vagrant/skylines/commands/import_/airspace.py", line 264, in import_openair
    from osgeo import ogr
ImportError: No module named osgeo
```

**Comment by lordfolken** [comment]
Closing as stale/wontfix in 2026 revitalization triage; reopen with fresh repro if still relevant.
