### ISSUE TITLE
Update python package requirements

### ISSUE THREAD

**Issue by Harry-R** [skylines-project/skylines#727]
I hit some problems when setting up skylines for development when executing `./manage.py db create`:
1. The `faker` package is missing, can be fixed by installing it
2.  `gevent` package seems to have a bug in the used version (1.0.1) and throws the following stack trace (can be fixed by updating gevent to 1.2.2):
```
Traceback (most recent call last):
  File "./manage.py", line 3, in <module>
    from skylines.commands import manager
  File "/home/harryr/Projects/skylines/skylines/skylines/commands/__init__.py", line 15, in <module>
    from .tracking import manager as tracking_manager
  File "/home/harryr/Projects/skylines/skylines/skylines/commands/tracking/__init__.py", line 7, in <module>
    from .generate_through_daemon import GenerateThroughDaemon
  File "/home/harryr/Projects/skylines/skylines/skylines/commands/tracking/generate_through_daemon.py", line 7, in <module>
    from skylines.tracking.server import datetime, FLAG_LOCATION, FLAG_ALTITUDE, TrackingFix, MAGIC, TYPE_FIX, set_crc
  File "/home/harryr/Projects/skylines/skylines/skylines/tracking/server.py", line 5, in <module>
    from gevent.server import DatagramServer
  File "/home/harryr/.envs/skylines/lib/python2.7/site-packages/gevent/server.py", line 6, in <module>
    from gevent.socket import EWOULDBLOCK, socket
  File "/home/harryr/.envs/skylines/lib/python2.7/site-packages/gevent/socket.py", line 659, in <module>
    from gevent.ssl import sslwrap_simple as ssl, SSLError as sslerror, SSLSocket as SSLType
  File "/home/harryr/.envs/skylines/lib/python2.7/site-packages/gevent/ssl.py", line 386, in <module>
    def get_server_certificate(addr, ssl_version=PROTOCOL_SSLv3, ca_certs=None):
NameError: name 'PROTOCOL_SSLv3' is not defined
```

**Comment by Harry-R** [comment]
The `faker` problem was caused by unclear installation instructions, see #729
