### ISSUE TITLE
Airspace import aborts when a server returns 404

### ISSUE THREAD

**Issue by kerel-fs** [skylines-project/skylines#898]
Trying to import the airspaces as described in [INSTALL.mapserver.md](https://github.com/skylines-project/skylines/blob/master/INSTALL.mapserver.md) fails:
```
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ pipenv run ./manage.py import airspace mapserver/airspace/airspace_list.txt mapserver/airspace/airspace_blacklist.txt
[...]
Downloading http://s289271336.onlinehome.fr/dossiers_ffvv/files/180330__AIRSPACE_France_2018-04.txt
Traceback (most recent call last):
  File "./manage.py", line 6, in <module>
    manager.run()
  File "/home/vagrant/.local/share/virtualenvs/vagrant-gKDsaKU3/local/lib/python2.7/site-packages/flask_script/__init__.py", line 423, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/home/vagrant/.local/share/virtualenvs/vagrant-gKDsaKU3/local/lib/python2.7/site-packages/flask_script/__init__.py", line 402, in handle
    return handle(app, *positional_args, **kwargs)
  File "/home/vagrant/.local/share/virtualenvs/vagrant-gKDsaKU3/local/lib/python2.7/site-packages/flask_script/commands.py", line 145, in handle
    return self.run(*args, **kwargs)
  File "/vagrant/skylines/commands/import_/airspace.py", line 133, in run
    self.import_airspace(url, country_code, file_type, debug)
  File "/vagrant/skylines/commands/import_/airspace.py", line 166, in import_airspace
    filename = self.download_file(filename, url)
  File "/vagrant/skylines/commands/import_/airspace.py", line 346, in download_file
    url])
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['wget', '-q', '-N', '--no-check-certificate', '-U', 'Mozilla/5.0 (Windows NT 5.1; rv:30.0) Gecko/20100101 Firefox/30.0', '-P', '/tmp/fr', '-O', '/tmp/fr/fr.openair', 'http://s289271336.onlinehome.fr/dossiers_ffvv/files/180330__AIRSPACE_France_2018-04.txt']' returned non-zero exit status 8
```

**Comment by lordfolken** [comment]
Closing as stale/wontfix in 2026 revitalization triage; reopen with fresh repro if still relevant.
