### ISSUE TITLE
run ./manage.py db create

### ISSUE THREAD

**Issue by ppker** [skylines-project/skylines#949]
hello, i use my macbook, my error is
```
(my_env-zMY7peW1) bash-3.2$ pipenv run ./manage.py db create
Traceback (most recent call last):
  File "./manage.py", line 3, in <module>
    from skylines.commands import manager
  File "/usr/local/var/python_code/yata_app/skylines/skylines/commands/__init__.py", line 8, in <module>
    from .shell import Shell
  File "/usr/local/var/python_code/yata_app/skylines/skylines/commands/shell.py", line 4, in <module>
    from skylines import model, database
  File "/usr/local/var/python_code/yata_app/skylines/skylines/model/__init__.py", line 7, in <module>
    from .airspace import Airspace
  File "/usr/local/var/python_code/yata_app/skylines/skylines/model/airspace.py", line 9, in <module>
    import xcsoar
ImportError: dlopen(/Users/yanzhipeng/.local/share/virtualenvs/skylines-VjQMxk9T/lib/python2.7/site-packages/xcsoar.so, 2): no suitable image found.  Did find:
	/Users/yanzhipeng/.local/share/virtualenvs/skylines-VjQMxk9T/lib/python2.7/site-packages/xcsoar.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x03
	/Users/yanzhipeng/.local/share/virtualenvs/skylines-VjQMxk9T/lib/python2.7/site-packages/xcsoar.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x03
(my_env-zMY7peW1) bash-3.2$ 
```

**Comment by Turbo87** [comment]
@ppker unfortunately due to the dependency on `xcsoar` Skylines currently only runs on Linux. You can use https://www.vagrantup.com/ with our `Vagrantfile` to generate a VM that can run it locally on your Macbook.

**Comment by ppker** [comment]
thank you, I'll give it a try.
